pipeline {
    agent none
    stages {
        stage('Build') {
            steps {
                sh "php -v"
            }
            agent {
                docker { image: 'php:8.1.9-apache'}
            }
        }
    }
}